version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tscli
    main: ./cmd/tscli
    goos:   [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -X github.com/jaxxstorm/tscli/pkg/version.Version={{.Version}}

archives:
  - id: default
    builds: [tscli]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: tscli
    tap:
      owner: jaxxstorm
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: bot@leebriggs.co.uk
    description: Interact with the Tailscale API from a CLI.
    homepage: https://github.com/jaxxstorm/tscli

scoop:
  - name: tscli
    bucket:
      owner: jaxxstorm
      name: scoop-bucket
    commit_author:
      name: GitHub Actions
      email: bot@leebriggs.co.uk
    description: Interact with the Tailscale API from a CLI.
    homepage: https://github.com/jaxxstorm/tscl
