package docs_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRequiredDocsPagesExist(t *testing.T) {
	required := []string{
		"docs/index.html",
		"docs/_sidebar.md",
		"docs/README.md",
		"docs/getting-started.md",
		"docs/command-reference.md",
		"docs/configuration.md",
		"docs/authentication.md",
	}

	for _, rel := range required {
		rel := rel
		t.Run(rel, func(t *testing.T) {
			assertFileExists(t, rel)
		})
	}
}

func TestDocsSidebarHasCoreLinks(t *testing.T) {
	data := readRepoFile(t, "docs/_sidebar.md")

	links := []string{
		"Getting Started",
		"Command Reference",
		"Configuration",
		"Authentication",
	}

	for _, link := range links {
		if !strings.Contains(data, link) {
			t.Fatalf("expected docs sidebar to include %q", link)
		}
	}
}

func TestGeneratedCommandDocsArtifactsExist(t *testing.T) {
	required := []string{
		"docs/commands/README.md",
		"docs/commands/_sidebar.md",
		"docs/commands/tscli.md",
		"docs/commands/tscli_config.md",
		"docs/commands/tscli_create.md",
		"docs/commands/tscli_get.md",
		"docs/commands/tscli_list.md",
		"docs/commands/tscli_set.md",
		"docs/commands/tscli_delete.md",
		"docs/commands/tscli_version.md",
	}

	for _, rel := range required {
		rel := rel
		t.Run(rel, func(t *testing.T) {
			assertFileExists(t, rel)
		})
	}

	readme := readRepoFile(t, "docs/commands/README.md")
	if !strings.Contains(readme, "Code generated by `make docs-generate`") {
		t.Fatalf("expected generated command README marker")
	}
}

func assertFileExists(t *testing.T, rel string) {
	t.Helper()
	if _, err := os.Stat(repoPath(rel)); err != nil {
		t.Fatalf("expected %s to exist: %v", rel, err)
	}
}

func readRepoFile(t *testing.T, rel string) string {
	t.Helper()
	b, err := os.ReadFile(repoPath(rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(b)
}

func repoPath(rel string) string {
	return filepath.Join("..", "..", filepath.FromSlash(rel))
}
