package cli_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAgentInitCreatesIntegrationAssetsWithoutAuth(t *testing.T) {
	repo := t.TempDir()

	res := executeCLINoDefaults(t, []string{"agent", "init", "--dir", repo}, nil)
	if res.err != nil {
		t.Fatalf("agent init: %v\nstderr:\n%s", res.err, res.stderr)
	}
	if !strings.Contains(res.stdout, "tscli agent integrations initialized") {
		t.Fatalf("expected init success output, got %q", res.stdout)
	}

	for _, rel := range []string{
		"AGENTS.md",
		"CLAUDE.md",
		".tscli/agent/manifest.yaml",
		".tscli/agent/commands.md",
		".codex/skills/tscli/SKILL.md",
		".github/skills/tscli/SKILL.md",
		".github/prompts/tscli-inspect.prompt.md",
		".github/prompts/tscli-operate.prompt.md",
	} {
		if _, err := os.Stat(filepath.Join(repo, filepath.FromSlash(rel))); err != nil {
			t.Fatalf("expected %s to exist: %v", rel, err)
		}
	}
}

func TestAgentInitDefaultsToGlobalInstall(t *testing.T) {
	home := t.TempDir()

	res := executeCLINoDefaults(t, []string{"agent", "init"}, map[string]string{"HOME": home})
	if res.err != nil {
		t.Fatalf("agent init: %v\nstderr:\n%s", res.err, res.stderr)
	}
	if !strings.Contains(res.stdout, "initialized (global)") {
		t.Fatalf("expected global init output, got %q", res.stdout)
	}

	for _, rel := range []string{
		".config/tscli/agent/manifest.yaml",
		".config/tscli/agent/commands.md",
		".codex/skills/tscli/SKILL.md",
		".claude/commands/tscli-inspect.md",
		".claude/commands/tscli-operate.md",
		".config/opencode/commands/tscli-inspect.md",
		".config/opencode/commands/tscli-operate.md",
	} {
		if _, err := os.Stat(filepath.Join(home, filepath.FromSlash(rel))); err != nil {
			t.Fatalf("expected %s to exist: %v", rel, err)
		}
	}
}

func TestAgentUpdateRefreshesInitializedBundle(t *testing.T) {
	repo := t.TempDir()

	initRes := executeCLINoDefaults(t, []string{"agent", "init", "--dir", repo, "--tool", "codex"}, nil)
	if initRes.err != nil {
		t.Fatalf("agent init: %v\nstderr:\n%s", initRes.err, initRes.stderr)
	}

	codexSkillPath := filepath.Join(repo, ".codex", "skills", "tscli", "SKILL.md")
	if err := os.WriteFile(codexSkillPath, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale codex skill: %v", err)
	}

	updateRes := executeCLINoDefaults(t, []string{"agent", "update", "--dir", repo}, nil)
	if updateRes.err != nil {
		t.Fatalf("agent update: %v\nstderr:\n%s", updateRes.err, updateRes.stderr)
	}
	if !strings.Contains(updateRes.stdout, "tscli agent integrations updated") {
		t.Fatalf("expected update success output, got %q", updateRes.stdout)
	}

	body, err := os.ReadFile(codexSkillPath)
	if err != nil {
		t.Fatalf("read refreshed codex skill: %v", err)
	}
	if !strings.Contains(string(body), "Code generated by `tscli agent init`; DO NOT EDIT.") {
		t.Fatalf("expected refreshed managed codex skill, got:\n%s", string(body))
	}
}

func TestAgentUpdateRefreshesGlobalInstall(t *testing.T) {
	home := t.TempDir()
	env := map[string]string{"HOME": home}

	initRes := executeCLINoDefaults(t, []string{"agent", "init", "--tool", "claude"}, env)
	if initRes.err != nil {
		t.Fatalf("agent init: %v\nstderr:\n%s", initRes.err, initRes.stderr)
	}

	inspectPath := filepath.Join(home, ".claude", "commands", "tscli-inspect.md")
	if err := os.WriteFile(inspectPath, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale claude command: %v", err)
	}

	updateRes := executeCLINoDefaults(t, []string{"agent", "update"}, env)
	if updateRes.err != nil {
		t.Fatalf("agent update: %v\nstderr:\n%s", updateRes.err, updateRes.stderr)
	}
	if !strings.Contains(updateRes.stdout, "updated (global)") {
		t.Fatalf("expected global update success output, got %q", updateRes.stdout)
	}

	body, err := os.ReadFile(inspectPath)
	if err != nil {
		t.Fatalf("read refreshed claude command: %v", err)
	}
	if !strings.Contains(string(body), "description: Inspect Tailscale control-plane state with tscli.") {
		t.Fatalf("expected refreshed managed claude command, got:\n%s", string(body))
	}
}
