package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

const (
	ToolGeneric  = "generic"
	ToolCodex    = "codex"
	ToolClaude   = "claude"
	ToolOpenCode = "opencode"
	ToolCopilot  = "copilot"

	ScopeLocal  = "local"
	ScopeGlobal = "global"

	managedBy      = "tscli-agent"
	managedMarker  = "Code generated by `tscli agent init`; DO NOT EDIT."
	manifestSchema = 1
	bundleVersion  = "v2"

	localManifestRelPath       = ".tscli/agent/manifest.yaml"
	localCommandCatalogRelPath = ".tscli/agent/commands.md"
	localAgentsRelPath         = "AGENTS.md"
	localClaudeRelPath         = "CLAUDE.md"
	localCodexSkillRelPath     = ".codex/skills/tscli/SKILL.md"
	localGitHubSkillRelPath    = ".github/skills/tscli/SKILL.md"
	localGitHubInspectRelPath  = ".github/prompts/tscli-inspect.prompt.md"
	localGitHubOperateRelPath  = ".github/prompts/tscli-operate.prompt.md"

	globalManifestRelPath        = ".config/tscli/agent/manifest.yaml"
	globalCommandCatalogRelPath  = ".config/tscli/agent/commands.md"
	globalCodexSkillRelPath      = ".codex/skills/tscli/SKILL.md"
	globalClaudeInspectRelPath   = ".claude/commands/tscli-inspect.md"
	globalClaudeOperateRelPath   = ".claude/commands/tscli-operate.md"
	globalOpenCodeInspectRelPath = ".config/opencode/commands/tscli-inspect.md"
	globalOpenCodeOperateRelPath = ".config/opencode/commands/tscli-operate.md"
)

var (
	allSupportedTools = []string{
		ToolGeneric,
		ToolCodex,
		ToolClaude,
		ToolOpenCode,
		ToolCopilot,
	}
	defaultLocalTools = []string{
		ToolGeneric,
		ToolCodex,
		ToolClaude,
		ToolOpenCode,
		ToolCopilot,
	}
	defaultGlobalTools = []string{
		ToolCodex,
		ToolClaude,
		ToolOpenCode,
	}
)

type InstallOptions struct {
	RootDir string
	Tools   []string
	Force   bool
}

type UpdateOptions struct {
	RootDir string
	Force   bool
}

type Result struct {
	RootDir       string
	InstallScope  string
	Tools         []string
	Files         []string
	ManifestPath  string
	CommandCount  int
	BundleVersion string
}

type Manifest struct {
	ManagedBy      string   `yaml:"managed-by"`
	SchemaVersion  int      `yaml:"schema-version"`
	BundleVersion  string   `yaml:"bundle-version"`
	InstallScope   string   `yaml:"install-scope"`
	Tools          []string `yaml:"tools"`
	Files          []string `yaml:"files"`
	CommandCount   int      `yaml:"command-count"`
	CommandCatalog string   `yaml:"command-catalog"`
}

type asset struct {
	Path    string
	Content string
}

type commandInfo struct {
	Path  string
	Short string
	Group string
}

type installTarget struct {
	Scope              string
	RootDir            string
	ManifestRelPath    string
	CommandCatalogPath string
}

func Init(root *cobra.Command, opts InstallOptions) (Result, error) {
	target, err := resolveInstallTarget(opts.RootDir)
	if err != nil {
		return Result{}, err
	}

	tools, err := normalizeTools(opts.Tools, target.Scope)
	if err != nil {
		return Result{}, err
	}

	return install(root, target, tools, opts.Force, loadManagedPaths(target))
}

func Update(root *cobra.Command, opts UpdateOptions) (Result, error) {
	target, err := resolveInstallTarget(opts.RootDir)
	if err != nil {
		return Result{}, err
	}

	manifest, err := loadManifest(target)
	if err != nil {
		return Result{}, err
	}

	tools, err := normalizeTools(manifest.Tools, target.Scope)
	if err != nil {
		return Result{}, err
	}

	return install(root, target, tools, opts.Force, pathSet(manifest.Files))
}

func SupportedTools() []string {
	return append([]string(nil), allSupportedTools...)
}

func install(root *cobra.Command, target installTarget, tools []string, force bool, managedPaths map[string]struct{}) (Result, error) {
	if root == nil {
		return Result{}, fmt.Errorf("root command is required")
	}

	commands := collectLeafCommands(root)
	assets := renderAssets(target, commands, tools)
	manifest := Manifest{
		ManagedBy:      managedBy,
		SchemaVersion:  manifestSchema,
		BundleVersion:  bundleVersion,
		InstallScope:   target.Scope,
		Tools:          append([]string(nil), tools...),
		Files:          append(assetPaths(assets), target.ManifestRelPath),
		CommandCount:   len(commands),
		CommandCatalog: target.CommandCatalogPath,
	}
	manifestAsset := asset{
		Path:    target.ManifestRelPath,
		Content: renderManifest(manifest),
	}
	nextManagedPaths := pathSet(manifest.Files)

	for _, generated := range assets {
		if err := writeManagedFile(target.RootDir, generated, force, managedPaths); err != nil {
			return Result{}, err
		}
	}
	if err := removeStaleManagedFiles(target.RootDir, managedPaths, nextManagedPaths); err != nil {
		return Result{}, err
	}
	if err := writeManagedFile(target.RootDir, manifestAsset, force, managedPaths); err != nil {
		return Result{}, err
	}

	return Result{
		RootDir:       target.RootDir,
		InstallScope:  target.Scope,
		Tools:         append([]string(nil), tools...),
		Files:         manifest.Files,
		ManifestPath:  target.ManifestRelPath,
		CommandCount:  len(commands),
		BundleVersion: bundleVersion,
	}, nil
}

func resolveInstallTarget(rootDir string) (installTarget, error) {
	if strings.TrimSpace(rootDir) == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return installTarget{}, fmt.Errorf("resolve home directory: %w", err)
		}
		if home == "" {
			return installTarget{}, fmt.Errorf("resolve home directory: empty home path")
		}
		return installTarget{
			Scope:              ScopeGlobal,
			RootDir:            home,
			ManifestRelPath:    globalManifestRelPath,
			CommandCatalogPath: globalCommandCatalogRelPath,
		}, nil
	}

	abs, err := filepath.Abs(rootDir)
	if err != nil {
		return installTarget{}, fmt.Errorf("resolve root dir: %w", err)
	}
	return installTarget{
		Scope:              ScopeLocal,
		RootDir:            abs,
		ManifestRelPath:    localManifestRelPath,
		CommandCatalogPath: localCommandCatalogRelPath,
	}, nil
}

func normalizeTools(tools []string, scope string) ([]string, error) {
	supported := supportedToolsForScope(scope)
	if len(tools) == 0 {
		return append([]string(nil), defaultToolsForScope(scope)...), nil
	}

	seen := map[string]struct{}{}
	normalized := make([]string, 0, len(tools))
	for _, tool := range tools {
		tool = strings.ToLower(strings.TrimSpace(tool))
		if tool == "" {
			continue
		}
		if !slices.Contains(supported, tool) {
			return nil, fmt.Errorf("unsupported tool %q for %s installs (supported: %s)", tool, scope, strings.Join(supported, ", "))
		}
		if _, ok := seen[tool]; ok {
			continue
		}
		seen[tool] = struct{}{}
		normalized = append(normalized, tool)
	}

	slices.SortFunc(normalized, func(a, b string) int {
		return toolOrder(a) - toolOrder(b)
	})
	return normalized, nil
}

func supportedToolsForScope(scope string) []string {
	switch scope {
	case ScopeGlobal:
		return append([]string(nil), defaultGlobalTools...)
	default:
		return append([]string(nil), defaultLocalTools...)
	}
}

func defaultToolsForScope(scope string) []string {
	switch scope {
	case ScopeGlobal:
		return defaultGlobalTools
	default:
		return defaultLocalTools
	}
}

func toolOrder(tool string) int {
	switch tool {
	case ToolGeneric:
		return 0
	case ToolCodex:
		return 1
	case ToolClaude:
		return 2
	case ToolOpenCode:
		return 3
	case ToolCopilot:
		return 4
	default:
		return 99
	}
}

func loadManifest(target installTarget) (Manifest, error) {
	path := filepath.Join(target.RootDir, filepath.FromSlash(target.ManifestRelPath))
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			switch target.Scope {
			case ScopeLocal:
				return Manifest{}, fmt.Errorf("agent manifest not found at %s; run `tscli agent init --dir %s` first", target.ManifestRelPath, target.RootDir)
			default:
				return Manifest{}, fmt.Errorf("agent manifest not found at %s; run `tscli agent init` first", target.ManifestRelPath)
			}
		}
		return Manifest{}, fmt.Errorf("read manifest: %w", err)
	}

	var manifest Manifest
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		return Manifest{}, fmt.Errorf("decode manifest: %w", err)
	}
	if manifest.ManagedBy != managedBy {
		return Manifest{}, fmt.Errorf("manifest at %s is not managed by tscli agent", target.ManifestRelPath)
	}
	switch manifest.SchemaVersion {
	case 0, manifestSchema:
	default:
		return Manifest{}, fmt.Errorf("manifest at %s uses unsupported schema-version %d (expected %d); rerun `tscli agent init` to regenerate it", target.ManifestRelPath, manifest.SchemaVersion, manifestSchema)
	}
	if manifest.InstallScope == "" {
		manifest.InstallScope = target.Scope
	}
	if manifest.InstallScope != target.Scope {
		if manifest.InstallScope == ScopeLocal {
			return Manifest{}, fmt.Errorf("manifest at %s is for a local install; rerun with `tscli agent update --dir %s`", target.ManifestRelPath, target.RootDir)
		}
		return Manifest{}, fmt.Errorf("manifest at %s is for a global install; rerun with `tscli agent update`", target.ManifestRelPath)
	}
	return manifest, nil
}

func collectLeafCommands(root *cobra.Command) []commandInfo {
	var commands []commandInfo
	var walk func(*cobra.Command)

	walk = func(cmd *cobra.Command) {
		if cmd.Run != nil || cmd.RunE != nil {
			fullPath := strings.TrimSpace(cmd.CommandPath())
			relativePath := strings.TrimSpace(strings.TrimPrefix(fullPath, root.Name()))
			if relativePath == "" {
				relativePath = root.Name()
			}
			group := relativePath
			if idx := strings.IndexByte(relativePath, ' '); idx >= 0 {
				group = relativePath[:idx]
			}
			commands = append(commands, commandInfo{
				Path:  fullPath,
				Short: strings.TrimSpace(cmd.Short),
				Group: group,
			})
		}

		children := append([]*cobra.Command(nil), cmd.Commands()...)
		slices.SortFunc(children, func(a, b *cobra.Command) int {
			return strings.Compare(a.Name(), b.Name())
		})
		for _, child := range children {
			if shouldExcludeCommand(child) {
				continue
			}
			walk(child)
		}
	}

	walk(root)
	slices.SortFunc(commands, func(a, b commandInfo) int {
		if groupCmp := strings.Compare(a.Group, b.Group); groupCmp != 0 {
			return groupCmp
		}
		return strings.Compare(a.Path, b.Path)
	})
	return commands
}

func shouldExcludeCommand(cmd *cobra.Command) bool {
	if cmd.Hidden {
		return true
	}
	switch cmd.Name() {
	case "help", "completion":
		return true
	default:
		return false
	}
}

func renderAssets(target installTarget, commands []commandInfo, tools []string) []asset {
	rendered := map[string]string{
		target.CommandCatalogPath: renderCommandCatalog(commands),
	}

	addAsset := func(path, content string) {
		rendered[path] = content
	}

	for _, tool := range tools {
		switch target.Scope {
		case ScopeGlobal:
			switch tool {
			case ToolCodex:
				addAsset(globalCodexSkillRelPath, renderCodexSkill(relativeReference(globalCodexSkillRelPath, target.CommandCatalogPath)))
			case ToolClaude:
				addAsset(globalClaudeInspectRelPath, renderClaudeCommand("Inspect Tailscale control-plane state with tscli.", relativeReference(globalClaudeInspectRelPath, target.CommandCatalogPath), true))
				addAsset(globalClaudeOperateRelPath, renderClaudeCommand("Operate Tailscale resources with tscli.", relativeReference(globalClaudeOperateRelPath, target.CommandCatalogPath), false))
			case ToolOpenCode:
				addAsset(globalOpenCodeInspectRelPath, renderOpenCodeCommand("Inspect Tailscale control-plane state with tscli.", relativeReference(globalOpenCodeInspectRelPath, target.CommandCatalogPath), true))
				addAsset(globalOpenCodeOperateRelPath, renderOpenCodeCommand("Operate Tailscale resources with tscli.", relativeReference(globalOpenCodeOperateRelPath, target.CommandCatalogPath), false))
			}
		default:
			switch tool {
			case ToolGeneric, ToolOpenCode:
				addAsset(localAgentsRelPath, renderAgentsFile(target, tools, len(commands)))
			case ToolCodex:
				addAsset(localCodexSkillRelPath, renderCodexSkill(relativeReference(localCodexSkillRelPath, target.CommandCatalogPath)))
			case ToolClaude:
				addAsset(localClaudeRelPath, renderClaudeProjectFile(relativeReference(localClaudeRelPath, target.CommandCatalogPath)))
			case ToolCopilot:
				addAsset(localGitHubSkillRelPath, renderGitHubSkill(relativeReference(localGitHubSkillRelPath, target.CommandCatalogPath)))
				addAsset(localGitHubInspectRelPath, renderInspectPrompt(relativeReference(localGitHubInspectRelPath, target.CommandCatalogPath)))
				addAsset(localGitHubOperateRelPath, renderOperatePrompt(relativeReference(localGitHubOperateRelPath, target.CommandCatalogPath)))
			}
		}
	}

	assets := make([]asset, 0, len(rendered))
	for path, content := range rendered {
		assets = append(assets, asset{Path: path, Content: content})
	}
	slices.SortFunc(assets, func(a, b asset) int {
		return strings.Compare(a.Path, b.Path)
	})
	return assets
}

func renderManifest(manifest Manifest) string {
	data, _ := yaml.Marshal(manifest)
	return "# Code generated by `tscli agent init`; DO NOT EDIT.\n\n" + string(data)
}

func renderAgentsFile(target installTarget, tools []string, commandCount int) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->\n\n")
	b.WriteString("# tscli Agent Instructions\n\n")
	b.WriteString("This repository is initialized for `tscli`-aware agents. Use `tscli` as the preferred interface for inspecting and operating the Tailscale control plane from this repo.\n\n")
	b.WriteString("## Workflow\n\n")
	b.WriteString("- For straightforward read requests, go directly to the most likely `tscli list ...` or `tscli get ...` command.\n")
	b.WriteString("- Check `tscli config show` or `tscli config profiles list` only when auth context is ambiguous, the user asks for it, or a command fails because of context.\n")
	b.WriteString("- Use `tscli <command> --help` only when the target leaf command or flags are genuinely unclear.\n")
	b.WriteString("- After mutations, report the exact `tscli` command you ran and the affected resources.\n")
	b.WriteString("- Refresh this integration bundle with `tscli agent update --dir .` whenever `tscli` gains new commands or guidance changes.\n\n")
	b.WriteString("## Generated Assets\n\n")
	b.WriteString(fmt.Sprintf("- Command catalog: `%s`\n", target.CommandCatalogPath))
	b.WriteString(fmt.Sprintf("- Bundle version: `%s`\n", bundleVersion))
	b.WriteString(fmt.Sprintf("- Install scope: `%s`\n", target.Scope))
	b.WriteString(fmt.Sprintf("- Supported tools in this install: `%s`\n", strings.Join(tools, "`, `")))
	b.WriteString(fmt.Sprintf("- Indexed leaf commands: `%d`\n\n", commandCount))
	b.WriteString("## Tool-Specific Surfaces\n\n")

	if hasTool(tools, ToolGeneric) {
		b.WriteString("- Generic project instructions: `AGENTS.md`\n")
	}
	if hasTool(tools, ToolOpenCode) {
		b.WriteString("- OpenCode project rules: `AGENTS.md`\n")
	}
	if hasTool(tools, ToolCodex) {
		b.WriteString("- Codex skill: `.codex/skills/tscli/SKILL.md`\n")
	}
	if hasTool(tools, ToolClaude) {
		b.WriteString("- Claude Code project memory: `CLAUDE.md`\n")
	}
	if hasTool(tools, ToolCopilot) {
		b.WriteString("- GitHub Copilot skill: `.github/skills/tscli/SKILL.md`\n")
		b.WriteString("- GitHub Copilot prompts: `.github/prompts/tscli-inspect.prompt.md`, `.github/prompts/tscli-operate.prompt.md`\n")
	}
	return b.String()
}

func renderCommandCatalog(commands []commandInfo) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->\n\n")
	b.WriteString("# tscli Agent Command Catalog\n\n")
	b.WriteString("Use this generated inventory to map tasks onto the current `tscli` command tree. When flags are unclear, follow up with `tscli <leaf-command> --help`.\n\n")

	currentGroup := ""
	for _, command := range commands {
		if command.Group != currentGroup {
			if currentGroup != "" {
				b.WriteString("\n")
			}
			currentGroup = command.Group
			b.WriteString(fmt.Sprintf("## `%s`\n\n", currentGroup))
		}
		if command.Short == "" {
			b.WriteString(fmt.Sprintf("- `%s`\n", command.Path))
			continue
		}
		b.WriteString(fmt.Sprintf("- `%s`: %s\n", command.Path, command.Short))
	}
	return b.String()
}

func renderCodexSkill(commandCatalogRef string) string {
	return strings.Join([]string{
		"---",
		"name: tscli",
		"description: Use tscli as the preferred interface for Tailscale control-plane inspection and operations.",
		"license: MIT",
		"compatibility: Requires tscli installed and configured for the target tailnet.",
		"metadata:",
		"  author: tscli",
		"  version: \"1.0\"",
		"  generatedBy: \"tscli-agent/v2\"",
		"---",
		"",
		"<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->",
		"",
		"Use `tscli` first whenever the user asks to inspect or operate Tailscale resources.",
		"",
		"## Operating rules",
		"",
		"1. Prefer `tscli` over ad hoc curl or handwritten API calls.",
		"2. For straightforward read requests, run the most likely `tscli list ...` or `tscli get ...` command immediately.",
		"3. Check `tscli config show` or `tscli config profiles list` only when auth context is ambiguous, the user asks for it, or a command fails because of context.",
		"4. Use `tscli <leaf-command> --help` only when the target command or flags are genuinely unclear, and default to at most one discovery command before the target command for read-only tasks.",
		"5. Keep progress updates terse; do not narrate obvious intermediate steps.",
		"6. Summarize the exact `tscli` commands executed and the resulting control-plane changes.",
		"",
		"## Command surface",
		"",
		fmt.Sprintf("Open `%s` for the generated command catalog.", commandCatalogRef),
		"",
	}, "\n")
}

func renderClaudeProjectFile(commandCatalogRef string) string {
	return strings.Join([]string{
		"# tscli Claude Instructions",
		"",
		"Use `tscli` first whenever the user asks to inspect or operate Tailscale resources from this repository.",
		"",
		"## Operating rules",
		"",
		"1. Prefer `tscli` over direct API calls when a command exists.",
		"2. For straightforward read requests, run the most likely `tscli list ...` or `tscli get ...` command immediately.",
		"3. Check `tscli config show` or `tscli config profiles list` only when auth context is ambiguous, the user asks for it, or a command fails because of context.",
		"4. Use `tscli <leaf-command> --help` only when the target command or flags are genuinely unclear.",
		"5. Keep progress updates terse and skip obvious intermediate narration.",
		"6. Summarize the exact `tscli` commands used and the observed state changes.",
		"",
		"## Command surface",
		"",
		fmt.Sprintf("Review @%s for the generated command catalog.", commandCatalogRef),
		"",
	}, "\n")
}

func renderGitHubSkill(commandCatalogRef string) string {
	return strings.Join([]string{
		"---",
		"name: tscli",
		"description: Use tscli to inspect and operate the Tailscale control plane from this repository.",
		"license: MIT",
		"compatibility: Requires tscli installed and configured for the target tailnet.",
		"metadata:",
		"  author: tscli",
		"  version: \"1.0\"",
		"  generatedBy: \"tscli-agent/v2\"",
		"---",
		"",
		"<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->",
		"",
		"Use `tscli` as the default interface for Tailscale control-plane work in this repository.",
		"",
		"## Operating rules",
		"",
		"1. Prefer `tscli` over direct API calls when a command exists.",
		"2. For straightforward read requests, run the most likely `tscli list ...` or `tscli get ...` command immediately.",
		"3. Check `tscli config show` only when auth context is ambiguous or a command fails because of context.",
		"4. Validate exact flags with `tscli <leaf-command> --help` only when needed.",
		"5. Keep progress updates terse and report the exact `tscli` command path used and the observed outcome.",
		"",
		"## Command surface",
		"",
		fmt.Sprintf("Open `%s` for the generated command catalog.", commandCatalogRef),
		"",
	}, "\n")
}

func renderInspectPrompt(commandCatalogRef string) string {
	return strings.Join([]string{
		"---",
		"description: Inspect Tailscale control-plane state using tscli.",
		"---",
		"",
		"<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->",
		"",
		"Use `tscli` for read-only Tailscale investigation in this repository.",
		"",
		"Workflow:",
		"- Confirm context with `tscli config show` or `tscli config profiles list` when needed.",
		"- Prefer `tscli list ...` and `tscli get ...`.",
		"- Use `tscli <leaf-command> --help` if flags are uncertain.",
		"- Summarize the exact commands run and the key fields returned.",
		"",
		fmt.Sprintf("Reference: `%s`", commandCatalogRef),
		"",
	}, "\n")
}

func renderOperatePrompt(commandCatalogRef string) string {
	return strings.Join([]string{
		"---",
		"description: Operate Tailscale resources using tscli.",
		"---",
		"",
		"<!-- Code generated by `tscli agent init`; DO NOT EDIT. -->",
		"",
		"Use `tscli` for Tailscale control-plane mutations in this repository.",
		"",
		"Workflow:",
		"- Inspect current state before changing it.",
		"- Prefer `tscli create ...`, `tscli set ...`, and `tscli delete ...` instead of direct API calls.",
		"- Check `tscli <leaf-command> --help` for the exact flags and payload expectations.",
		"- After the mutation, summarize the exact command path used and the resulting state change.",
		"",
		fmt.Sprintf("Reference: `%s`", commandCatalogRef),
		"",
	}, "\n")
}

func renderClaudeCommand(description string, commandCatalogRef string, readOnly bool) string {
	body := renderCommandTemplate(commandCatalogRef, readOnly)
	return strings.Join([]string{
		"---",
		fmt.Sprintf("description: %s", description),
		"argument-hint: [task]",
		"---",
		"",
		body,
	}, "\n")
}

func renderOpenCodeCommand(description string, commandCatalogRef string, readOnly bool) string {
	body := renderCommandTemplate(commandCatalogRef, readOnly)
	return strings.Join([]string{
		"---",
		fmt.Sprintf("description: %s", description),
		"---",
		"",
		body,
	}, "\n")
}

func renderCommandTemplate(commandCatalogRef string, readOnly bool) string {
	verb := "inspect"
	workflow := []string{
		"- Run the most likely `tscli list ...` or `tscli get ...` command immediately.",
		"- Check `tscli config show` or `tscli config profiles list` only when auth context is ambiguous or a command fails because of context.",
		"- Check `tscli <leaf-command> --help` only if flags are uncertain.",
	}
	if !readOnly {
		verb = "operate on"
		workflow = []string{
			"- Confirm context with `tscli config show` or `tscli config profiles list` when credentials or active tailnet matter.",
			"- Inspect current state before mutating it.",
			"- Prefer `tscli create ...`, `tscli set ...`, and `tscli delete ...` over direct API calls.",
			"- Validate exact flags with `tscli <leaf-command> --help` only when needed.",
		}
	}

	lines := []string{
		fmt.Sprintf("Use `tscli` to %s Tailscale resources for the user's request: $ARGUMENTS", verb),
		"",
		"Generated command catalog:",
		fmt.Sprintf("@%s", commandCatalogRef),
		"",
		"Workflow:",
	}
	lines = append(lines, workflow...)
	lines = append(lines,
		"- Keep progress updates terse and summarize the exact `tscli` commands used and the observed result.",
		"",
	)
	return strings.Join(lines, "\n")
}

func writeManagedFile(rootDir string, generated asset, force bool, managedPaths map[string]struct{}) error {
	path := filepath.Join(rootDir, filepath.FromSlash(generated.Path))

	if existing, err := os.ReadFile(path); err == nil {
		if string(existing) == generated.Content {
			return nil
		}
		_, knownManagedPath := managedPaths[generated.Path]
		if !force && !knownManagedPath && !isManagedContent(string(existing)) {
			return fmt.Errorf("%s exists and is not managed by tscli agent; rerun with --force to overwrite it", generated.Path)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", generated.Path, err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create parent directories for %s: %w", generated.Path, err)
	}
	if err := os.WriteFile(path, []byte(generated.Content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", generated.Path, err)
	}
	return nil
}

func isManagedContent(content string) bool {
	return strings.Contains(content, managedMarker) || strings.Contains(content, "managed-by: "+managedBy)
}

func assetPaths(assets []asset) []string {
	paths := make([]string, 0, len(assets))
	for _, generated := range assets {
		paths = append(paths, generated.Path)
	}
	return paths
}

func loadManagedPaths(target installTarget) map[string]struct{} {
	manifest, err := loadManifest(target)
	if err != nil {
		return map[string]struct{}{}
	}
	return pathSet(manifest.Files)
}

func removeStaleManagedFiles(rootDir string, previousPaths, nextPaths map[string]struct{}) error {
	for relPath := range previousPaths {
		if _, keep := nextPaths[relPath]; keep {
			continue
		}
		path := filepath.Join(rootDir, filepath.FromSlash(relPath))
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove stale managed file %s: %w", relPath, err)
		}
		pruneEmptyParents(rootDir, filepath.Dir(path))
	}
	return nil
}

func pathSet(paths []string) map[string]struct{} {
	set := make(map[string]struct{}, len(paths))
	for _, path := range paths {
		set[path] = struct{}{}
	}
	return set
}

func pruneEmptyParents(rootDir, dir string) {
	rootDir = filepath.Clean(rootDir)
	for dir != "." && dir != string(filepath.Separator) && dir != rootDir {
		if err := os.Remove(dir); err != nil {
			return
		}
		dir = filepath.Dir(dir)
	}
}

func relativeReference(fromRelPath, toRelPath string) string {
	fromDir := filepath.Dir(filepath.FromSlash(fromRelPath))
	rel, err := filepath.Rel(fromDir, filepath.FromSlash(toRelPath))
	if err != nil {
		return toRelPath
	}
	return filepath.ToSlash(rel)
}

func hasTool(tools []string, tool string) bool {
	return slices.Contains(tools, tool)
}
